### ISSUE TITLE
Make it work with rust-tapyrus update_on_bitcoin_0.31.x branch

### ISSUE THREAD

**Issue by rantan** [chaintope/rust-miniscript#1]
# Todos

* [ ] make mater branch passing the CI
* [ ] Remove `#[ignore] attribute on some tests that are failure because of removal Taproot and SegWit.
     * p2wsh, p2wpkh, tr の代わりに p2pkh, p2sh などを使ってテストを書き直す必要がある。
* [ ] Update examples. 
* [ ] Enable compiler feature
* [ ] Make fuzzing tests
* [ ] Make Integration test work
